######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 16 00:18:29 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += send_msg.h
SOURCES += main.cpp send_msg.cpp
